version: '3.9'
services:
  server:
    deploy:
      replicas: 4
    build:
      context: ./
      dockerfile: ./dockerfile
    environment:
      PORT: 3000
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres/postgres?schema=public
    restart: always
    depends_on:
      - postgres
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./static:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"