service:
 name: ticketing
package:
  individually: true
plugins:
 - serverless-webpack
 - serverless-plugin-optimize
 - serverless-offline

provider:
 name: aws
 runtime: nodejs14.x
 region: ap-east-1

functions:
 main: # The name of the lambda function
   handler: src/lambda.handler
   events:
     - http:
         method: any
         path: /{any+}

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
    includeModules: true