useDotenv: true
service: ticketing
package:
  individually: true
plugins:
 - serverless-plugin-typescript
 - serverless-offline

provider:
 name: aws
 runtime: nodejs14.x
 region: ap-east-1
 lambdaHashingVersion: 20201221

functions:
 main: # The name of the lambda function
   handler: src/lambda.handler
   events:
     - http:
         method: any
         path: /{any+}
